# This assumes that you have build the backend and frontend from ex 1.14
# with the names "front" and "back"

version: '3.8'
services:
    backend:
        image: back
        environment:
            - REQUEST_ORIGIN=http://localhost:5000
            - GIN_MODE=release
            - REDIS_HOST=redis
            - POSTGRES_HOST=postgres
            - POSTGRES_USER=testuser
            - POSTGRES_PASSWORD=testpass
            - POSTGRES_DATABASE=testdb
        restart: unless-stopped
        container_name: backend
    frontend:
        image: front
        environment:
            - REACT_APP_BACKEND_URL=http://localhost:8080
        restart: unless-stopped
        container_name: frontend
    redis:
        image: redis:latest
        restart: unless-stopped
        container_name: redis
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_USER=testuser
            - POSTGRES_PASSWORD=testpass
            - POSTGRES_DB=testdb
        restart: unless-stopped
        container_name: postgres
    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf        
        container_name: nginx_proxy
