version: '3.8'
services:
    backend:
        build: backend
        environment:
            - REQUEST_ORIGIN=http://localhost:80
            - GIN_MODE=release
            - REDIS_HOST=redis
            - POSTGRES_HOST=postgres
            - POSTGRES_USER=testuser
            - POSTGRES_PASSWORD=testpass
            - POSTGRES_DATABASE=testdb
        restart: unless-stopped
        container_name: backend
    frontend:
        build: frontend
        ports:
            - 80:80
        environment:
            - REACT_APP_BACKEND_URL=http://localhost:8080
        restart: unless-stopped
        container_name: frontend
    redis:
        image: redis:latest
        restart: unless-stopped
        container_name: redis
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_USER=testuser
            - POSTGRES_PASSWORD=testpass
            - POSTGRES_DB=testdb
        restart: unless-stopped
        container_name: postgres
